name: release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
      - name: Instal build deps
        run: |
          python -m pip install -U pip hatch hatch-vcs
          pip install -e .
      - name: Run smoke import test
        run: python test_import.py

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: 
          python-version: "3.13"
      - name: Build wheel + sdist
        run: |
          python -m pip install -U pip hatch hatch-vcs twine
          hatch build
          twine check dist/*
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*
  
  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          prerelease: ${{ contains(github.ref_name, 'rc') || contains(github.ref_name, 'a') || contains(github.ref_name, 'b') || contains(github.ref_name, 'dev') }}

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Determine repository
        id: repo
        run: |
          TAG="${GITHUB_REF_NAME}"
          if [[ "$TAG" =~ [a-zA-Z] ]]; then
            echo "repo=testpypi" >> "$GITHUB_OUTPUT"
          else
            echo "repo=pypi" >> "$GITHUB_OUTPUT"
          fi
      - name: Publish to TestPyPI
        if: steps.repo.outputs.repo == 'testpypi'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
      - name: Publish to PyPI
        if: steps.repo.outputs.repo == 'pypi'
        uses: pypa/gh-action-pypi-publish@release/v1